name: Build and Push DevContainers

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
          - name: doris
            path: doris

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase owner
        id: vars
        run: echo "owner_lc=${IMAGE_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.container.path }}
          file: ./${{ matrix.container.path }}/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner_lc }}/devcontainer-${{ matrix.container.name }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=DevContainer for ${{ matrix.container.name }}
            org.opencontainers.image.licenses=MIT

